# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:32
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default='DEFAULT VALUE')),
                ('ID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('m_type', models.CharField(max_length=50)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_geos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default='DEFAULT VALUE')),
                ('geo', models.URLField(blank=True, default='DEFAULT VALUE')),
                ('user', models.IntegerField(default=0)),
                ('user_url', models.URLField(blank=True, default='DEFAULT VALUE')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
