# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geos',
            name='multi_coords',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
