# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 21:25
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0002_geos_multi_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geos_Multi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default='DEFAULT VALUE')),
                ('ID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('m_type', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='geos',
            old_name='coordinates',
            new_name='geom',
        ),
        migrations.RemoveField(
            model_name='geos',
            name='multi_coords',
        ),
    ]
