# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0003_auto_20160509_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='geos',
            name='raw',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='geos_multi',
            name='raw',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
