# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0005_auto_20160510_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geos_multi',
            name='raw',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
