# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0007_auto_20160510_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('json_data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='geos',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='geos_multi',
            name='raw',
        ),
    ]
