# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0009_auto_20160510_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.IntegerField()),
            ],
        ),
    ]
